spring:
  application:
    name: logguard-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/logguard
    username: logguard
    password: logguard123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080